name: Bump requirements.txt
on:
  pull_request:
    paths:
      - 'pyproject.toml'
  workflow_dispatch:

permissions:
  pull-requests: write
  
jobs:
  bump_requirements:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      if: ${{ github.actor == 'dependabot[bot]' }}
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Set up Python
      if: ${{ github.actor == 'dependabot[bot]' }}
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
          python-version: '3.11'

    - name: Install Poetry
      if: ${{ github.actor == 'dependabot[bot]' }}
      uses: abatilo/actions-poetry@7b6d33e44b4f08d7021a1dee3c044e9c253d6439 # v3.0.0
      with:
        poetry-version: '1.7.1'
    
    - name: Bump Python dependencies
      if: ${{ github.actor == 'dependabot[bot]' }}
      run: |
        poetry update
        poetry export --format requirements.txt --output requirements.txt
        poetry export --format requirements.txt --output requirements.dev --with dev
        git config --global user.name 'dependabot[bot]'
        git config --global user.email 'dependabot[bot]@users.noreply.github.com'
        git add requirements.txt requirements.dev
        if [ -z "$(git status --porcelain)" ]; then 
          echo 'No changes to commit on this run'
          exit 0
        else
          poetry version patch
          git add pyproject.toml
          git commit -m "build(deps): Bump requirements.txt and poetry version"
          git push
        fi
